[package]
name = "condvar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "1.11.1"
tokio = { version = "1.33.0", features = ["full"] }
tokio-stream = "0.1.14"
futures = "0.3.28"
reqwest = "0.11.22"

[[example]]
name = "condvar"

[workspace]
members = ["mandelbrot"]

[workspace.dependencies]
